clawer/captcha/urls.py
from django.conf.urls import patterns, include, url



urlpatterns = patterns('captcha.views',
    # Examples:
    url(r'^$', 'index'),
    url(r'^labeled/$', 'labeled'),
    url(r'^labeled/(?P<page>\d+)/$', 'labeled'),
    url(r'^all/labeled/$', 'all_labeled'),
    
    url(r"^make/label/$", "make_label"),
)

clawer/clawer/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings



admin.autodiscover()


#apis 
user_api_urls = patterns("clawer.apis.user", 
    url(r"^login/$", "login"),
    url(r"^logout/$", "logout"),
    url(r"^keepalive/$", "keepalive"),
    url(r"^is/logined/$", "is_logined"),
    
    url(r"^my/menus/$", "get_my_menus"),

)

logger_api_urls = patterns("clawer.apis.logger",
    url(r"^all/$", "all"),
)

monitor_api_urls = patterns("clawer.apis.monitor",
    url(r"^task/stat/$", "task_stat"),
    url(r"^hour/$", "hour"),
    url(r"^day/$", "day"),
    url(r"^hour/echarts/$", "hour_echarts"),
    url(r"^day/echarts/$", "day_echarts"),
)

home_api_urls = patterns("clawer.apis.home",
    url(r"^clawer/all/$", "clawer_all"),
    url(r"^clawer/add/$", "clawer_add"),
    
    url(r"^clawer/task/$", "clawer_task"),
    url(r"^clawer/task/add/$", "clawer_task_add"),
    url(r"^clawer/task/reset/$", "clawer_task_reset"),
    
    url(r"^clawer/task/generator/update/$", "clawer_task_generator_update"),
    url(r"^clawer/task/generator/history/$", "clawer_task_generator_history"),
    url(r"^clawer/generate/log/$", "clawer_generate_log"),
    
    url(r"^clawer/analysis/history/$", "clawer_analysis_history"),
    url(r"^clawer/analysis/log/$", "clawer_analysis_log"),
    url(r"^clawer/analysis/update/$", "clawer_analysis_update"),
    
    url(r"^clawer/setting/update/$", "clawer_setting_update"),
    
    url(r"^clawer/download/log/$", "clawer_download_log"),
)

apis_urls = patterns("clawer.apis", 
    url(r"^user/", include(user_api_urls)),
    url(r"^home/", include(home_api_urls)),
    url(r"^logger/", include(logger_api_urls)),
    url(r"^monitor/", include(monitor_api_urls)),
)



#views
logger_urls = patterns("clawer.views.logger",
    url(r"^$", "index"),
)

monitor_urls = patterns("clawer.views.monitor",
    url(r"^realtime/dashboard/$", "realtime_dashboard"),
    url(r"^hour/$", "hour"),
    url(r"^day/$", "day"),
)


urlpatterns = patterns('clawer.views.home',
    # Examples:
    url(r'^$', 'index'),
    
    url(r'^clawer/$', "clawer"),
    url(r'^clawer/all/$', "clawer_all"),
    url(r"^clawer/download/log/$", "clawer_download_log"),
    url(r"^clawer/task/$", "clawer_task"),
    url(r"^clawer/analysis/log/$", "clawer_analysis_log"),
    url(r"^clawer/generate/log/$", "clawer_generate_log"),
    url(r"^clawer/setting/$", "clawer_setting"),
    
    url(r"^logger/", include(logger_urls)),
    url(r"^monitor/", include(monitor_urls)),
    
    url(r'^apis/', include(apis_urls)),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r"^captcha/", include("captcha.urls")),
    
    url(r"^enterprise/", include("enterprise.urls")),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)


if settings.DEBUG:
    urlpatterns += patterns("",
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True }),
    )
    
    
handler404 = 'clawer.views.home.page_404'
handler500 = 'clawer.views.home.page_500'

clawer/captcha/models.py
#encoding=utf-8

from django.db import models
from django.conf import settings
import urlparse

# Create your models here.

class Category(models.Model):
    (NORMAL, 
     YUNSUAN, 
     ZHIHU, 
     JIANGSHU,
     TIANJIN,
     JIANGXI,
     CHONGQING,
     SICHUAN,
     GUIZHOU,
     XIZHUANG,
     QINHAI,
     NINGXIA,
     XINJIANG,
     QUANGUO,
     GUANGDONG,
     SHANGHAI,
     HEBEI,
     SHANXI,
     NEIMENGGU,
     LIAONING,
     JILIN,
     HEILONGJIANG,
     ZHEJIANG,
     ANHUI,
     FUJIAN,
     SHANDONG,
     GUANGXI,
     HAINAN,
     HENAN,
     ALL,
     ALL_1,
     ) = range(1, 32)
    
    full_choices = (
        (NORMAL, u"北京字母", 'http://qyxy.baic.gov.cn/CheckCodeCaptcha?currentTimeMillis=1444875766745&num=87786', 300),
        (YUNSUAN, u"运算类型", "http://qyxy.baic.gov.cn/CheckCodeYunSuan?currentTimeMillis=1447655192940&num=48429", 300),
        (ZHIHU, u"知乎字母", "http://www.zhihu.com/captcha.gif?r=1448087287415", 300),
        (JIANGSHU, u"江苏", "http://www.jsgsj.gov.cn:58888/province/rand_img.jsp?type=7", 300),
        (TIANJIN, u"天津", "http://tjcredit.gov.cn/verifycode", 300),
        (JIANGXI, u"江西", "http://gsxt.jxaic.gov.cn/ECPS/verificationCode.jsp", 300),
        (CHONGQING, u"重庆", "http://gsxt.cqgs.gov.cn/sc.action?width=130&height=40&fs=23&t=1449473139130", 300),
        (SICHUAN, u"四川", 'http://gsxt.scaic.gov.cn/ztxy.do?method=createYzm&dt=1449473634428&random=1449473634428', 300),
        (GUIZHOU, u"贵州", 'http://gsxt.gzgs.gov.cn/search!generateCode.shtml?validTag=searchImageCode&1449473693892', 300),
        (XIZHUANG, u"西藏", 'http://gsxt.xzaic.gov.cn/validateCode.jspx?type=0&id=0.6980565481876813', 300),
        (QINHAI, u"青海", 'http://218.95.241.36/validateCode.jspx?type=0&id=0.9130336582967944', 300),
        (NINGXIA, u"宁夏", 'http://gsxt.ngsh.gov.cn/ECPS/verificationCode.jsp?_=1449473855952', 300),
        (XINJIANG, u"新疆", 'http://gsxt.xjaic.gov.cn:7001/ztxy.do?method=createYzm&dt=1449473880582&random=1449473880582', 300),
        (QUANGUO, u"全国-汉字", 'http://gsxt.saic.gov.cn/zjgs/captcha?preset=&ra=0.6737781641715337', 1000),
        (GUANGDONG, u"广东", 'http://gsxt.gdgs.gov.cn/aiccips/verify.html?random=0.6461621058211715', 1000),
        (SHANGHAI, u"上海", 'https://www.sgs.gov.cn/notice/captcha?preset=1&ra=0.13763015669048162', 1000),
        (HEBEI, u"河北", "http://www.hebscztxyxx.gov.cn/notice/captcha?preset=1&ra=0.12507317386321537", 300),
        (SHANXI, u"山西", 'http://218.26.1.108/validateCode.jspx?type=1&id=0.5561280730741579', 1000),
        (NEIMENGGU, u"内蒙古", 'http://www.nmgs.gov.cn:7001/aiccips/verify.html?random=0.15379660368246195', 1000),
        (LIAONING, u"辽宁", 'http://gsxt.lngs.gov.cn/saicpub/commonsSC/loginDC/securityCode.action?tdate=47736', 300),
        (JILIN, u"吉林", 'http://211.141.74.198:8081/aiccips/securitycode?0.9858144849658483', 1000),
        (HEILONGJIANG, u"黑龙江", 'http://gsxt.hljaic.gov.cn/validateCode.jspx?type=1&id=0.37630681760147366', 1000),
        (ZHEJIANG, u"浙江", '', 0),
        (ANHUI, u"安徽", 'http://www.ahcredit.gov.cn/validateCode.jspx?type=1&id=0.41052326137836004', 1000),
        (FUJIAN, u"福建", 'http://wsgs.fjaic.gov.cn/creditpub/captcha?preset=str-00&ra=0.7105599333444296', 300),
        (SHANDONG, u"山东", 'http://218.57.139.24/securitycode?0.07734315576514572', 1000),
        (GUANGXI, u"广西", 'http://gxqyxygs.gov.cn/validateCode.jspx?type=1&id=0.49213323240661666', 1000),
        (HAINAN, u"海南", "", 0),
        (HENAN, u"河南", "http://222.143.24.157/validateCode.jspx?type=1&id=0.9717317246571591", 1000),
        (ALL, u"全国工商总局-字母", 'http://gsxt.saic.gov.cn/zjgs/captcha?preset=1&ra=0.6737781641715337', 600),
        (ALL_1, u"全国工商总局-字母1", 'http://gsxt.saic.gov.cn/zjgs/captcha?preset=1&ra=0.6737781641715337', 300),
    )
    
    name = models.CharField(max_length=128)
    url = models.CharField(max_length=1024)
    max_number = models.IntegerField(default=0)
    
    class Meta:
        app_label = "captcha"
    

class Captcha(models.Model):
    url = models.URLField()
    category = models.IntegerField()
    image_hash = models.CharField(max_length=32)
    label_count = models.IntegerField(default=0)
    add_datetime = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        app_label = "captcha"
    
    def image_url(self):
        return urlparse.urljoin(settings.MEDIA_URL, "captcha/%d/%s" % (self.category, self.image_hash))
    
    def label_logs(self):
        return LabelLog.objects.filter(captcha=self)
    
    def as_json(self):
        result = {"id": self.id,
            "category": self.category,
            "image_hash": self.image_hash,
            "labels": [x.label for x in self.label_logs()],
            "image_url": self.image_url(),
        }
        return result
        
        
class LabelLog(models.Model):
    captcha = models.ForeignKey(Captcha)
    label = models.CharField(max_length=32)
    ip = models.IPAddressField()
    add_datetime = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        app_label = "captcha"
        

clawer/captcha/forms.py
#encoding=utf-8

from django import forms
from html5helper.fields import CharField, IntegerField

clawer/captcha/views.py
#encoding=utf-8
# Create your views here.

import random
import traceback

from html5helper.utils import get_request_ip, do_paginator
from html5helper.decorator import render_template, render_json
from captcha.models import Captcha, LabelLog, Category
from django.core.urlresolvers import reverse



def index(request):
    title = u"图片识别"
    category_id = request.GET.get("category_id")
    
    random_count = 50
    if category_id:
        category_id = int(category_id)
        category = Category.objects.get(id=category_id)
        captchas = Captcha.objects.filter(label_count__lt=3, category=category_id)[:random_count]
        labeled_captcha_count = Captcha.objects.filter(label_count__gt=2, category=category_id).count()
        captcha_count = Captcha.objects.filter(category=category_id).all().count()
    else:
        captchas = Captcha.objects.filter(label_count__lt=3)[:random_count]
        labeled_captcha_count = Captcha.objects.filter(label_count__gt=2).count()
        captcha_count = Captcha.objects.all().count()
        category = None
        
    if len(captchas) > 1:
        random_index = random.randint(0, len(captchas))
        captcha = captchas[random_index]
    elif len(captchas) == 1:
        captcha = captchas[0]
    else:
        captcha = None
        
    categories = Category.objects.all()
    
    return render_template("captcha/index.html", request=request, labeled_captcha_count=labeled_captcha_count, catpcha_count=captcha_count, title=title,
                           captcha=captcha, categories=categories, category=category)
    
    
def labeled(request, page=1):
    qs = Captcha.objects.filter(label_count__gt=2)
    pager = do_paginator(qs, page, 20)
    prefix = reverse("captcha.views.labeled")
    
    return render_template("captcha/labeled.html", request=request, pager=pager, prefix=prefix)


@render_json
def make_label(request):
    captcha_id = request.POST.get("captcha_id")
    label = request.POST.get("label")
    
    try:
        captcha = Captcha.objects.get(id=captcha_id)
    except:
        return {"is_ok":False, "reason": traceback.format_exc(1)}
    
    if not label.strip():
        return {"is_ok":False, "reason":u"文字不能为空"}
    
    captcha.label_count += 1
    captcha.save()
    
    LabelLog.objects.create(captcha=captcha, label=label, ip=get_request_ip(request))
    return {"is_ok":True}


@render_json
def all_labeled(request):
    category = int(request.GET.get("category"))
    qs = Captcha.objects.filter(label_count__gt=2, category=category)
    
    return {"is_ok":True, "captchas":[x.as_json() for x in qs]}

clawer/captcha/templates/captcha/index.html
{% extends "base.html" %}
{% load static %}



{% block content %}

<ul class="list-inline">
    <li>
        <!-- Single button -->
		<div class="btn-group">
		  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		    {% if category %}{{category.name}}{% else %}请选择分组{% endif %} <span class="caret"></span>
		  </button>
		  <ul class="dropdown-menu">
		    {% for item in categories %}
		    <li><a href="{% url captcha.views.index %}?category_id={{item.id}}">{{item.name}}</a></li>
		    {% endfor %}
		  </ul>
		</div>
    </li>
    <li>已标记：{{labeled_captcha_count}}</li>
    <li>总图片：{{catpcha_count|default:0}}</li>
    <li><a href="{% url captcha.views.labeled %}">看看我们的战绩</a></li>
    <li>图片地址： <a href="{{ category.url }}" target="_blank">{{ category.url }}</a></li>
</ul>


{% if captcha %}
<div class="panel panel-info">
    <div class="panel-body">
    
        <div id="tips"></div>
        
        <ul class="list-inline">
            <li><img src="{{ captcha.image_url }}" /></li>
            <li>请写下图片中的文字</li>
            <li><a href="" class="btn btn-default">换一个</a></li>
        </ul>
        
        <form class="form-inline" style="margin-top:30px;" id="form" method="post">
		  <div class="form-group">
		      <input type="hidden" class="form-control" name="captcha_id" value="{{captcha.id}}">
		      <input type="text" class="form-control" id="id_label" name="label" placeholder="请写下图片中的文字">
		  </div>
		  <a class="btn btn-primary" href="javascript:void(0)" id="submitBtn">提交</a>
		</form>
		
    </div>
</div>
{% else %}
<div class="panel panel-info">
    <div class="panel-body text-center">
        <h1>大功告成</h1>
    </div>
</div>
{% endif %}

<script>
$(document).ready(function(){
	$("#id_label").focus();
	
	$("#id_label").keypress(function(e){   
		var code = e.keyCode || e.which;
		if(code == 13) { //Enter keycode
		   doSubmit();
	       return false;
		}
	
    });

	$("#submitBtn").bind("click", function(e){
		doSubmit(); 
	});
	
	function doSubmit() {
		$("#submitBtn").html("提交中");
		$("#submitBtn").addClass("disabled");
		
		var url = "{% url captcha.views.make_label %}";
		
		if(!$("#id_label").val()) {
			show_tips("danger", "文字是空的");
			return;
		}

		$.ajax({  
			 url: url, 
			 data: $("#form").serialize(),
			 type: "POST", 
			 dataType:'json', 
			 success: function(resp) {
				 if(resp.is_ok == false) {
					 show_tips("danger", resp.reason);
					 return
				 }
				 
				 var timeout = 1000;
				 show_tips("success", "Thanks! 稍等" + (timeout/1000) + "秒后...刷新");
				 
				 window.setTimeout(function() {
					 window.location.href = window.location.href;
				 }, timeout);
				 
			 }, 
			  
		 });
	}
	
});

function show_tips(tag, message) {
	var content = [];
	
	if(tag == "success") {
		content = [
		    "<div class='alert alert-success'>",
		    message,
		    "</div>"
		];
	} else if(tag == "danger") {
		content = [
		    "<div class='alert alert-danger'>",
		    message,
		    "</div>"
		];
	}
	
	$("#tips").html(content.join(""));
	
	window.setTimeout(function(){
		close_tips();
	}, 30000);
}

function close_tips() {
	$("#tips").html("");
}

</script>


{% endblock %}

clawer/captcha/templates/captcha/labeled.html
{% extends "base.html" %}
{% load static %}
{% load pagination %}


{% block content %}

<div>
    <pre>
    接口地址： {% url captcha.views.all_labeled %}
    参数：category=${category}
    </pre>
</div>

<table class="table table-striped">
    {% for item in pager %}
    <tr>
        <td><img src="{{item.image_url}}" /></td>
        
        <td>
	        <ul class="list-inline">
	        {% for label_log in item.label_logs %}
	            <li>{{label_log.label}}</li>
	        {% endfor %}
	        </ul>
        </td>
        
    </tr>
    {% endfor %}
</table>


{% pagination pager prefix request %}

{% endblock %}