clawer/clawer/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings



admin.autodiscover()


#apis 
user_api_urls = patterns("clawer.apis.user", 
    url(r"^login/$", "login"),
    url(r"^logout/$", "logout"),
    url(r"^keepalive/$", "keepalive"),
    url(r"^is/logined/$", "is_logined"),
    
    url(r"^my/menus/$", "get_my_menus"),

)

logger_api_urls = patterns("clawer.apis.logger",
    url(r"^all/$", "all"),
)

monitor_api_urls = patterns("clawer.apis.monitor",
    url(r"^task/stat/$", "task_stat"),
    url(r"^hour/$", "hour"),
    url(r"^day/$", "day"),
    url(r"^hour/echarts/$", "hour_echarts"),
    url(r"^day/echarts/$", "day_echarts"),
)

home_api_urls = patterns("clawer.apis.home",
    url(r"^clawer/all/$", "clawer_all"),
    url(r"^clawer/add/$", "clawer_add"),
    
    url(r"^clawer/task/$", "clawer_task"),
    url(r"^clawer/task/add/$", "clawer_task_add"),
    url(r"^clawer/task/reset/$", "clawer_task_reset"),
    
    url(r"^clawer/task/generator/update/$", "clawer_task_generator_update"),
    url(r"^clawer/task/generator/history/$", "clawer_task_generator_history"),
    url(r"^clawer/generate/log/$", "clawer_generate_log"),
    
    url(r"^clawer/analysis/history/$", "clawer_analysis_history"),
    url(r"^clawer/analysis/log/$", "clawer_analysis_log"),
    url(r"^clawer/analysis/update/$", "clawer_analysis_update"),
    
    url(r"^clawer/setting/update/$", "clawer_setting_update"),
    
    url(r"^clawer/download/log/$", "clawer_download_log"),
)

apis_urls = patterns("clawer.apis", 
    url(r"^user/", include(user_api_urls)),
    url(r"^home/", include(home_api_urls)),
    url(r"^logger/", include(logger_api_urls)),
    url(r"^monitor/", include(monitor_api_urls)),
)



#views
logger_urls = patterns("clawer.views.logger",
    url(r"^$", "index"),
)

monitor_urls = patterns("clawer.views.monitor",
    url(r"^realtime/dashboard/$", "realtime_dashboard"),
    url(r"^hour/$", "hour"),
    url(r"^day/$", "day"),
)


urlpatterns = patterns('clawer.views.home',
    # Examples:
    url(r'^$', 'index'),
    
    url(r'^clawer/$', "clawer"),
    url(r'^clawer/all/$', "clawer_all"),
    url(r"^clawer/download/log/$", "clawer_download_log"),
    url(r"^clawer/task/$", "clawer_task"),
    url(r"^clawer/analysis/log/$", "clawer_analysis_log"),
    url(r"^clawer/generate/log/$", "clawer_generate_log"),
    url(r"^clawer/setting/$", "clawer_setting"),
    
    url(r"^logger/", include(logger_urls)),
    url(r"^monitor/", include(monitor_urls)),
    
    url(r'^apis/', include(apis_urls)),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r"^captcha/", include("captcha.urls")),
    
    url(r"^enterprise/", include("enterprise.urls")),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)


if settings.DEBUG:
    urlpatterns += patterns("",
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True }),
    )
    
    
handler404 = 'clawer.views.home.page_404'
handler500 = 'clawer.views.home.page_500'

clawer/clawer/models.py
#encoding=utf-8
import copy
import os
import logging
import datetime
import codecs
import redis
import urlparse
import traceback
import json

from django.contrib.auth.models import User as DjangoUser
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save, pre_save
from django.dispatch.dispatcher import receiver
from django.core.cache import cache

from clawer.utils import Download, UrlCache, DownloadQueue
from html5helper import redis_cluster



class Clawer(models.Model):
    (STATUS_ON, STATUS_OFF) = range(1, 3)
    STATUS_CHOICES = (
        (STATUS_ON, u"启用"),
        (STATUS_OFF, u"下线"),
    )
    name = models.CharField(max_length=128)
    info = models.CharField(max_length=1024)
    customer = models.CharField(max_length=128, blank=True, null=True)
    status = models.IntegerField(default=STATUS_ON, choices=STATUS_CHOICES)
    add_datetime = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = "clawer"

    def as_json(self):
        result = {"id": self.id,
            "name": self.name,
            "info": self.info,
            "customer": self.customer,
            "status": self.status,
            "status_name": self.status_name(),
            "result_url": self.result_url(),
            "add_datetime": self.add_datetime.strftime("%Y-%m-%d %H:%M:%S")
        }

        runing =  self.runing_task_generator()
        result["runing_task_generator"] = runing.as_json() if runing else None

        analysis = self.runing_analysis()
        result["runing_analysis"] = analysis.as_json() if analysis else None

        result["setting"] = self.settings().as_json()

        return result

    def runing_task_generator(self):
        try:
            result = ClawerTaskGenerator.objects.filter(clawer=self, status=ClawerTaskGenerator.STATUS_ON)[0]
        except:
            result = None

        return result

    def runing_analysis(self):
        try:
            result = ClawerAnalysis.objects.filter(clawer=self, status=ClawerAnalysis.STATUS_ON)[0]
        except:
            result = None

        return result

    def status_name(self):
        for item in self.STATUS_CHOICES:
            if item[0] == self.status:
                return item[1]

        return ""

    def settings(self):
        return ClawerSetting.objects.get_or_create(clawer=self)[0]

    def cached_settings(self):
        key = "%d_cached_setting" % self.id
        cache_time = 3600
        result = cache.get(key)
        if result:
            return result

        result = self.settings()
        if result:
            cache.set(key, result, cache_time)
        return result

    def result_url(self):
        return urlparse.urljoin(settings.CLAWER_RESULT_URL, "%d" % self.id)


class ClawerAnalysis(models.Model):
    (STATUS_ON, STATUS_OFF) = range(1, 3)
    STATUS_CHOICES = (
        (STATUS_ON, u"启用"),
        (STATUS_OFF, u"下线"),
    )
    clawer = models.ForeignKey(Clawer)
    code = models.TextField()  #python code
    status = models.IntegerField(default=STATUS_ON, choices=STATUS_CHOICES)
    add_datetime = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = "clawer"

    def as_json(self):
        result = {"id": self.id,
            "code": self.code,
            "status": self.status,
            "status_name": self.status_name(),
            "add_datetime": self.add_datetime.strftime("%Y-%m-%d %H:%M:%S"),
        }
        return result

    def status_name(self):
        for item in self.STATUS_CHOICES:
            if item[0] == self.status:
                return item[1]

        return ""

    def code_dir(self):
        path = os.path.join(settings.MEDIA_ROOT, "codes")
        if os.path.exists(path) is False:
            os.makedirs(path, 0775)
        return path

    def product_path(self):
        return os.path.join(self.code_dir(), "%d_analysis.py" % self.clawer_id)

    def write_code(self, path):
        if os.path.exists(path):
            os.remove(path)
        with codecs.open(path, "w", "utf-8") as f:
            f.write(self.code)


class ClawerAnalysisLog(models.Model):
    (STATUS_FAIL, STATUS_SUCCESS) = range(1, 3)
    STATUS_CHOICES = (
        (STATUS_FAIL, u"失败"),
        (STATUS_SUCCESS, u"成功"),
    )
    clawer = models.ForeignKey(Clawer)
    analysis = models.ForeignKey(ClawerAnalysis)
    task = models.ForeignKey('ClawerTask')
    status = models.IntegerField(default=0, choices=STATUS_CHOICES)
    failed_reason = models.CharField(max_length=10240, null=True, blank=True)
    hostname = models.CharField(null=True, blank=True, max_length=16)
    result = models.TextField(null=True, blank=True)
    add_datetime = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = "clawer"

    def as_json(self):
        result = {"id":self.id,
            "clawer": self.clawer.as_json(),
            "analysis": self.analysis.as_json(),
            "task": self.task.as_json(),
            "status": self.status,
            "status_name": self.status_name(),
            "failed_reason": self.failed_reason,
            "result": self.result,
            "hostname": self.hostname,
            "add_datetime": self.add_datetime.strftime("%Y-%m-%d %H:%M:%S"),
        }
        return result

    def status_name(self):
        for item in self.STATUS_CHOICES:
            if item[0] == self.status:
                return item[1]

        return ""

    def result_path(self):
        parent = os.path.join("/tmp", "clawer_analysis")
        if os.path.exists(parent) is False:
            os.mkdir(parent)
        return os.path.join(parent, "%d.analysis" % self.task.id)


class ClawerDownloadLog(models.Model):
    (STATUS_FAIL, STATUS_SUCCESS) = range(1, 3)
    STATUS_CHOICES = (
        (STATUS_FAIL, u"失败"),
        (STATUS_SUCCESS, u"成功"),
    )
    clawer = models.ForeignKey(Clawer)
    task = models.ForeignKey('ClawerTask')
    status = models.IntegerField(default=0, choices=STATUS_CHOICES)
    failed_reason = models.CharField(max_length=10240, null=True, blank=True)
    content_bytes = models.IntegerField(default=0)
    content_encoding = models.CharField(null=True, blank=True, max_length=32)
    hostname = models.CharField(null=True, blank=True, max_length=16)
    spend_time = models.IntegerField(default=0) #unit is microsecond
    add_datetime = models.DateTimeField(auto_now=True)

    class Meta:
        app_label = "clawer"

    def as_json(self):
        result = {"id":self.id,
            "clawer": self.clawer.as_json(),
            "task": self.task.as_json(),
            "status": self.status,
            "status_name": self.status_name(),
            "hostname": self.hostname,
            "failed_reason": self.failed_reason,
            "content_bytes": self.content_bytes,
            "content_encoding": self.content_encoding,
            "spend_time": self.spend_time,
            "add_datetime": self.add_datetime.strftime("%Y-%m-%d %H:%M:%S"),
        }
        return result

    def status_name(self):
        for item in self.STATUS_CHOICES:
            if item[0] == self.status:
                return item[1]

        return ""


class ClawerTaskGenerator(models.Model):
    (STATUS_ALPHA, STATUS_BETA, STATUS_PRODUCT, STATUS_ON, STATUS_OFF, STATUS_TEST_FAIL) = range(1, 7)
    STATUS_CHOICES = (
        (STATUS_ALPHA, u"alpha"),
        (STATUS_BETA, u"beta"),
        (STATUS_PRODUCT, u"production"),
        (STATUS_ON, u"启用"),
        (STATUS_OFF, u"下线"),
        (STATUS_TEST_FAIL, u"测试失败"),
    )
    clawer = models.ForeignKey(Clawer)
    code = models.TextField()  #python code
    cron = models.CharField(max_length=128)
    status = models.IntegerField(default=STATUS_ALPHA, choices=STATUS_CHOICES)
    add_datetime = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = "clawer"
        ordering = ["-id"]

    def as_json(self):
        result = {"id": self.id,
            "clawer_id": self.clawer_id,
            "code": self.code,
            "cron": self.cron,
            "status": self.status,
            "status_name": self.status_name(),
            "add_datetime": self.add_datetime.strftime("%Y-%m-%d %H:%M:%S"),
        }
        return result

    def status_name(self):
        for item in self.STATUS_CHOICES:
            if item[0] == self.status:
                return item[1]
        return ""

    def code_dir(self):
        path = os.path.join(settings.MEDIA_ROOT, "codes")
        if os.path.exists(path) is False:
            os.makedirs(path, 0775)
        return path

    def alpha_path(self):
        return os.path.join(self.code_dir(), "%d_alpha.py" % self.clawer_id)

    def product_path(self):
        return os.path.join(self.code_dir(), "%d_product.py" % self.clawer_id)

    def write_code(self, path):
        with codecs.open(path, "w", "utf-8") as f:
            f.write(self.code)


class ClawerGenerateLog(models.Model):
    (STATUS_FAIL, STATUS_SUCCESS) = range(1, 3)
    STATUS_CHOICES = (
        (STATUS_FAIL, u"失败"),
        (STATUS_SUCCESS, u"成功"),
    )
    clawer = models.ForeignKey(Clawer)
    task_generator = models.ForeignKey(ClawerTaskGenerator)
    status = models.IntegerField(default=0, choices=STATUS_CHOICES)
    failed_reason = models.CharField(max_length=10240, null=True, blank=True)
    content_bytes = models.IntegerField(default=0)
    spend_msecs = models.IntegerField(default=0) #unit is microsecond
    hostname = models.CharField(null=True, blank=True, max_length=16)
    add_datetime = models.DateTimeField(auto_now=True)

    class Meta:
        app_label = "clawer"

    def status_name(self):
        for item in self.STATUS_CHOICES:
            if item[0] == self.status:
                return item[1]
        return ""

    def as_json(self):
        result = {
            "id":self.id,
            "clawer": self.clawer.as_json(),
            "task_generator": self.task_generator.as_json(),

clawer/clawer/forms.py
#encoding=utf-8

from django import forms

from clawer.models import Clawer, ClawerSetting
from clawer.utils import Download



class AddClawer(forms.Form):
    name = forms.CharField(max_length=128)
    info = forms.CharField(max_length=1024)
    customer = forms.CharField(max_length=128)
    

class UpdateClawerTaskGenerator(forms.Form):
    clawer = forms.ModelChoiceField(queryset=Clawer.objects)
    code_file = forms.FileField()
    cron = forms.CharField(max_length=64)
    
    
class UpdateClawerAnalysis(forms.Form):
    clawer = forms.ModelChoiceField(queryset=Clawer.objects)
    code_file = forms.FileField()
    

class AddClawerTask(forms.Form):
    clawer = forms.ModelChoiceField(queryset=Clawer.objects)
    uri = forms.CharField(max_length=4096)
    cookie = forms.CharField(max_length=4096, required=False)
    

class UpdateClawerSetting(forms.Form):
    clawer = forms.ModelChoiceField(queryset=Clawer.objects)
    dispatch = forms.IntegerField()
    analysis = forms.IntegerField()
    proxy = forms.CharField(max_length=4096, required=False)
    cookie = forms.CharField(max_length=4096, required=False)
    download_js = forms.CharField(max_length=4096, required=False)
    download_engine = forms.ChoiceField(choices=Download.ENGINE_CHOICES)
    status = forms.ChoiceField(choices=Clawer.STATUS_CHOICES)
    prior = forms.ChoiceField(choices=ClawerSetting.PRIOR_CHOICES)
    report_mails = forms.CharField(max_length=1024, required=False)
    

clawer/clawer/views.py
#encoding=utf-8


from html5helper.decorator import render_template


def index(request):
    return render_template("index.html", request=request)


def clawer(request):
    return render_template("clawer/index.html", request=request)

clawer/clawer/views/home.py
#encoding=utf-8


from html5helper.decorator import render_template


def index(request):
    return render_template("index.html", request=request)


def clawer(request):
    return render_template("clawer/index.html", request=request)


def clawer_all(request):
    return render_template("clawer/all.html", request=request)


def clawer_task(request):
    return render_template("clawer/task.html", request=request)


def clawer_download_log(request):
    return render_template("clawer/download_log.html", request=request)


def clawer_analysis_log(request):
    return render_template("clawer/analysis_log.html", request=request)


def clawer_generate_log(request):
    return render_template("clawer/generate_log.html", request=request)


def clawer_setting(request):
    return render_template("clawer/setting.html", request=request)


def page_404(request):
    return render_template("404.html", request=request)


def page_500(request):
    return render_template("500.html", request=request)

clawer/clawer/views/logger.py
#coding=utf-8


from html5helper.decorator import render_template


def index(request):
    return render_template("clawer/logger/index.html", request=request)

clawer/clawer/views/monitor.py
#encoding=utf-8


from html5helper.decorator import render_template


def realtime_dashboard(request):
    return render_template("clawer/monitor/realtime_dashboard.html", request=request)


def hour(request):
    return render_template("clawer/monitor/hour.html", request=request)


def day(request):
    return render_template("clawer/monitor/day.html", request=request)

clawer/clawer/templates/clawer/base.html
{% load static %}


<!DOCTYPE html>
<html>
<head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        
        <title>Nice Clawer Boss</title>
        <link rel="stylesheet" href="{% static 'clawer/css/common.css' %}" media="screen">
        
        <link rel="stylesheet" type="text/css" href="{% static 'clawer/easyui/themes/default/easyui.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'clawer/easyui/themes/icon.css' %}">
        
        <script type="text/javascript" src="{% static 'clawer/easyui/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'clawer/easyui/jquery.easyui.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'clawer/easyui/locale/easyui-lang-zh_CN.js' %}"></script>
        <script type="text/javascript" src="{% static 'clawer/form/jquery.form.js' %}"></script>
        
        {% block extra_css %}{% endblock %}
        
        {% block extra_js %}{% endblock %}
</head>



{% block body %}


<body class="easyui-layout" data-options="fit: true,border : false">

    {% block content %}{% endblock %}
    
    
    
 
<script>


$(document).ready(function(){
	
});
</script>
<!-- end login window -->
      
</body>
{% endblock %}

</html>

clawer/clawer/templates/clawer/setting.html
{% extends "clawer/base.html"%}
{% load static %}


{% block body %}
<body>

<div id="toolbar">
    <a href="#" class="easyui-menubutton" menu="#operate">操作</a>
    
    <select id="status_select" class="easyui-combobox" name="status" style="width:200px;">
	    <option value="">全部</option>
	    <option value="1">在线</option>
	    <option value="2">下线</option>
	</select>
    
    <input type="number" id="id_input" name="id" placeholder="ID" class="easyui-textbox" />
    <a href="javascript:void(0)" id="search_btn" class="easyui-linkbutton" data-options="iconCls:'icon-search'">搜索</a>
</div>


<div id="operate">
    <div id="update_btn" iconCls="icon-edit">更新</div>
    <div id="add_btn" iconCls="icon-add">新增</div>
</div>


<table id="grid" class="easyui-datagrid" style="width:100%;height:100%"
        fitColumns="true" url="{% url clawer.apis.home.clawer_all %}" showFooter="true"
        data-options="singleSelect:true,collapsible:true,method:'get'" rownumbers="true" pagination="true"
        toolbar="#toolbar" rowStyler="rowStyle">
        
    <thead data-options="frozen:true">
        <tr>
            <th data-options="field:'id',width:80" sortable="true">ID</th>
            <th data-options="field:'name',">名称</th>
        </tr>
    </thead>
    <thead>
        <tr>
            <th data-options="field:'status_name',">状态</th>
            <th data-options="field:'setting'," formatter="formatSettingDispatch">每次分发任务数</th>
            <th data-options="field:'s1'," formatter="formatSettingAnalysis">每次分析数</th>
            <th data-options="field:'sproxy'," formatter="formatSettingProxy">Proxy</th>
            <th data-options="field:'sprior'," formatter="formatSettingPrior">优先级</th>
            <th data-options="field:'engine'," formatter="formatSettingDownloadEngine">下载引擎</th>
            <th data-options="field:'cookie'," formatter="formatSettingCookie">Cookie</th>
            <th data-options="field:'crontab'," formatter="formatCrontab">任务生成器Cron</th>
            <th data-options="field:'report_mails'," formatter="formatSettingReportMails">报警邮箱</th>
            <th data-options="field:'s2'," formatter="formatSettingLastUpdateDatetime">最后修改时间</th>
        </tr>
    </thead>    
</table>


<!-- update form -->
<div id="update_win" class="easyui-window" title="更新参数" closed="true" style="width:80%;height:60%;padding:5px;">

    <h1></h1>
    
    <form method="post" id="update_form" action="{% url clawer.apis.home.clawer_setting_update %}">
        <table style="width:100%;">
            <tr>
                <td>每次分发任务数</td>
                <td>
                    <input name="dispatch" class="easyui-numberbox" style="width: 50%;">
				    <input id="clawer" name="clawer" type="hidden" />
				</td>
            </tr>
            <tr>
                <td>每次分析数</td>
                <td><input name="analysis" class="easyui-numberbox" style="width: 50%;"></td>
            </tr>
            <tr>
                <td>报警邮箱 <small>(多个邮箱以空格分离)</small></td>
                <td><input name="report_mails" class="easyui-textbox" style="width: 80%; height: 30px;" placeholder="多个邮箱以空格分离" /></td>
            </tr>
            <tr>
                <td>Proxy</td>
                <td><input name="proxy" class="easyui-textbox" style="width: 60%; height: 80px;" placeholder="多个proxy，请换行" multiline="true" /></td>
            </tr>
            <tr>
                <td>Cookie</td>
                <td><input name="cookie" class="easyui-textbox" style="width: 60%; height: 80px;" placeholder="Cookie" multiline="true" /></td>
            </tr>
            <tr>
                <td>下载后执行JS</td>
                <td>
                    <input name="download_js" class="easyui-textbox" style="width: 60%; height: 100px;" placeholder="Cookie" multiline="true" />
                    <p><small>只有在下载引擎为selenium时候，才会执行</small></p>
                </td>
            </tr>
            <tr>
                <td>下载引擎</td>
                <td>
                    <select id="id_download_engine" class="easyui-combobox" name="download_engine" style="width:200px;">
					    <option value="requests">requests</option>
					    <option value="selenium">selenium</option>
					    <option value="phantomjs">phantomjs</option>
					</select>
                </td>
            </tr>
            <tr>
                <td>状态</td>
                <td>
                    <select id="id_status" class="easyui-combobox" name="status" style="width:200px;">
					    <option value="1">启用</option>
					    <option value="2">下线</option>
					</select>
                </td>
            </tr>
            <tr>
                <td>优先级</td>
                <td>
                    <select id="id_prior" class="easyui-combobox" name="prior" style="width:200px;">
					    <option value="0">普通</option>
					    <option value="1">紧急</option>
					    <option value="2">海外</option>
					</select>
                </td>
            </tr>
            <tr>
                <td><button class="easyui-linkbutton" style="width: 50px" type="submit">保存</button></td>
                <td></td>
            </tr>
        </table>
    </form>
    
</div>
<!-- update form end -->


<!-- add form -->
<div id="add_win" class="easyui-window" title="增加爬虫" closed="true" style="width:80%;height:60%;padding:5px;">

    <form method="post" id="add_form" action="{% url clawer.apis.home.clawer_add %}">
        <table style="width:100%;">
            <tr>
                <td>爬虫名</td>
                <td>
                    <input name="name" class="easyui-textbox" style="width: 60%; height: 30px;" />
				</td>
            </tr>
            <tr>
                <td>客户</td>
                <td><input name="customer" class="easyui-textbox" style="width: 60%; height: 30px;" /></td>
            </tr>
            
            <tr>
                <td>描述</td>
                <td><input name="info" class="easyui-textbox" style="width: 70%; height: 80px;" placeholder="多个proxy，请换行" multiline="true" /></td>
            </tr>
            <tr>
                <td><button class="easyui-linkbutton" style="width: 50px" type="submit">增加</button></td>
                <td></td>
            </tr>
        </table>
    </form>
    
</div>
<!-- add form end -->





<script type="text/javascript">

function formatSettingDispatch(val, row) {
	if(!row.setting) {
		return "-";
	}
	
	return row.setting.dispatch;
}


function formatSettingReportMails(val, row) {
	if(!row.setting) {
		return "-";
	}
	
	return row.setting.report_mails;
}


function formatSettingPrior(val, row) {
	if(!row.setting) {
		return "-";
	}
	
	return row.setting.prior_name;
}


function formatSettingCookie(val, row) {
	if(!row.setting) {
		return "-";
	}
	
	return row.setting.cookie;
}


function formatSettingAnalysis(val, row) {
	if(!row.setting) {
		return "";
	}
	return row.setting.analysis;
}


function formatSettingLastUpdateDatetime(val, row) {
	if(!row.setting) {
		return "";
	}
	return row.setting.last_update_datetime;
}

function formatSettingProxy(val, row) {
	if(!row.setting) {
		return "";
	}
	return row.setting.proxy;
}

function formatSettingDownloadEngine(val, row) {
	if(!row.setting) {
		return "";
	}
	
	var js = "-";
	if(row.setting.download_js) {
		js = row.setting.download_js.substr(0, 10) + "...";
	}
	var content = [
        row.setting.download_engine,
        "(",
        js,
        ")"
	];
	return content.join(" ");
}

function formatCrontab(val, row) {
	if(!row.runing_task_generator) {
		return "";
	}
	return row.runing_task_generator.cron;
}


function rowStyle(index, row) {
	console.debug("index ", index, ", row status ", row.status, ", row ", row);
	if(row.status == 2) {
		return {"class":"danger"};
	}
}


$(document).ready(function(){
	
	$("#search_btn").bind("click", function(e){
		
        $("#grid").datagrid("load", {
            obj_id: $("#id_input").val()
        });
        
    });
	
	$("#update_btn").bind("click", function(e){
		var row = $("#grid").datagrid("getSelected");
		if(!row) {
			return $.messager.alert('Warning', '请先选择一条数据');
		}
		
		$("#update_win").find("#clawer").val(row.id);
		$("#update_win").find("h1").html("ID: "+ row.id + ", " + row.name);
		$("#update_form").form("load", {
			clawer:row.id, 
		    dispatch: row.setting.dispatch,
		    analysis: row.setting.analysis,
		    proxy: row.setting.proxy,
		    cookie: row.setting.cookie,
		    download_js: row.setting.download_js,
		    report_mails: row.setting.report_mails
		});
		$("#id_download_engine").combobox("setValue", row.setting.download_engine);
		$("#id_status").combobox("setValue", row.status);
		$("#id_prior").combobox("setValue", row.setting.prior);
		
		$("#update_win").window("open");
	});
	
	$("#update_form").submit(function(){
		
    	$(this).ajaxSubmit({
            dataType: "json",
            success: function(resp, status, xhr, frm) {
                if(!resp.is_ok) {
                    $.messager.alert('warning', resp.reason);
                    return;
                }
                
                $("#update_form").form("reset");
                $("#update_form").form("clear");
                $("#grid").datagrid("reload");
                $("#update_win").window("close");
            }
        });
    	
    	return false;
    });
	
	
	$("#status_select").combobox({
		onSelect: function(record) {
			console.debug(record);
			$("#grid").datagrid("load", {
	            status: record.value
	        });
		}
	});
	
	
	$("#add_btn").bind("click", function(e){
		$("#add_win").window("open");
	});
	
	$("#add_form").submit(function(){
		
    	$(this).ajaxSubmit({
            dataType: "json",
            success: function(resp, status, xhr, frm) {
                if(!resp.is_ok) {
                    $.messager.alert('warning', resp.reason);
                    return;
                }
                
                $("#add_form").form("reset");
                $("#add_form").form("clear");
                
                $("#grid").datagrid("reload");
                $("#add_win").window("close");
            }
        });
    	
    	return false;
    });
	
	
});

</script>



</body>
{% endblock %}